# Config file for automatic testing at travis-ci.org

sudo: false
language: python

install:
  - pip install tox

script:
  - tox

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip
